/**
 * Trade types for Monsoon Chat Trade Ideation MVP
 */

/**
 * Represents a single position in a trade basket.
 * Positions can be either LONG or SHORT depending on which array they're in.
 */
export interface Position {
  /** Token symbol (e.g., 'ETH', 'BTC') */
  symbol: string;
  /** Full name of the token (e.g., 'Ethereum', 'Bitcoin') */
  name: string;
  /** Weight as a percentage (0-100) of this position within its side */
  weight: number;
  /** Daily trading volume in USD */
  dailyVolume: number;
}

/**
 * Represents a complete trade proposal with LONG and SHORT positions.
 * Generated by GPT-4 based on user's trading thesis.
 */
export interface TradeProposal {
  /** Unique identifier for the proposal */
  id: string;
  /** Array of positions to go LONG on */
  longPositions: Position[];
  /** Array of positions to go SHORT on */
  shortPositions: Position[];
  /** Stop-loss percentage (e.g., 15 means -15%) */
  stopLoss: number;
  /** Take-profit percentage (e.g., 25 means +25%) */
  takeProfit: number;
  /** Timestamp when the proposal was created */
  createdAt: Date;
}

/**
 * Represents a message in the chat history.
 * Used for maintaining conversation context with GPT-4.
 */
export interface ChatMessage {
  /** Unique identifier for the message */
  id: string;
  /** Role of the message sender */
  role: 'user' | 'assistant';
  /** Text content of the message */
  content: string;
  /** Optional trade proposal attached to assistant messages */
  tradeProposal?: TradeProposal;
}
