/**
 * Trade types for Monsoon Chat Trade Ideation MVP
 */

/**
 * Represents a single position in a trade basket.
 * Positions can be either LONG or SHORT depending on which array they're in.
 */
export interface Position {
  /** Token symbol (e.g., 'ETH', 'BTC') */
  symbol: string;
  /** Full name of the token (e.g., 'Ethereum', 'Bitcoin') */
  name: string;
  /** Weight as a percentage (0-100) of this position within its side */
  weight: number;
  /** Daily trading volume in USD */
  dailyVolume: number;
}

/**
 * Represents a recommended token for trade modification suggestions.
 * Pre-computed by AI and attached to the original TradeProposal.
 * Task 1.3: Create RecommendedToken interface
 */
export interface RecommendedToken {
  /** Token symbol (e.g., 'SOL', 'FET') */
  symbol: string;
  /** Full name of the token (e.g., 'Solana', 'Fetch.ai') */
  name: string;
  /** Explanation of why this token is relevant to the trade theme */
  relevance: string;
}

/**
 * Represents a token available on Hyperliquid exchange.
 * Used for token search and selection in the modification modal.
 * Task 1.4: Create HyperliquidToken interface
 */
export interface HyperliquidToken {
  /** Token symbol (e.g., 'ETH', 'BTC') */
  symbol: string;
  /** Full name of the token */
  name: string;
  /** Daily trading volume in USD */
  dailyVolumeUsd: number;
}

/**
 * Represents a complete trade proposal with LONG and SHORT positions.
 * Generated by GPT-4 based on user's trading thesis.
 * Task 1.2: Extended with recommendedTokens and isLatest fields
 */
export interface TradeProposal {
  /** Unique identifier for the proposal */
  id: string;
  /** Array of positions to go LONG on */
  longPositions: Position[];
  /** Array of positions to go SHORT on */
  shortPositions: Position[];
  /** Stop-loss percentage (e.g., 15 means -15%) */
  stopLoss: number;
  /** Take-profit percentage (e.g., 25 means +25%) */
  takeProfit: number;
  /** Timestamp when the proposal was created */
  createdAt: Date;
  /** Up to 3 recommended tokens for trade modification suggestions */
  recommendedTokens?: RecommendedToken[];
  /** Flag indicating if this is the latest proposal (only latest can be modified) */
  isLatest?: boolean;
}

/**
 * Represents a request to modify an existing trade proposal.
 * Sent to the API when user saves modifications from the modal.
 * Task 1.5: Create ModificationRequest interface
 */
export interface ModificationRequest {
  /** ID of the original proposal being modified */
  originalProposalId: string;
  /** Modified array of LONG positions */
  longPositions: Position[];
  /** Modified array of SHORT positions */
  shortPositions: Position[];
}

/**
 * Represents a message in the chat history.
 * Used for maintaining conversation context with GPT-4.
 */
export interface ChatMessage {
  /** Unique identifier for the message */
  id: string;
  /** Role of the message sender */
  role: 'user' | 'assistant';
  /** Text content of the message */
  content: string;
  /** Optional trade proposal attached to assistant messages */
  tradeProposal?: TradeProposal;
}
